// <auto-generated />
namespace UniversityDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class change_StudentId_to_null : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_StudentId_to_null));
        
        string IMigrationMetadata.Id
        {
            get { return "201906061425004_change_StudentId_to_null"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
